FROM microsoft/windowsservercore
ADD {{rootfs}} /
EXPOSE 9631 {{exposes}}
RUN {{hab_path}} pkg install {{installed_primary_svc_ident}} --install-hook force
ENTRYPOINT ["{{hab_path}}", "sup", "run", "{{primary_svc_ident}}"]
