[package]
name = "habitat_sup"
version = "0.0.0"
authors = ["Adam Jacob <adam@chef.io>", "Jamie Winsor <reset@chef.io>", "Fletcher Nichol <fnichol@chef.io>", "Joshua Timberman <joshua@chef.io>", "Dave Parfitt <dparfitt@chef.io>"]
build = "./build.rs"
workspace = "../../"

[lib]
name = "habitat_sup"

[[bin]]
name = "hab-sup"
path = "src/main.rs"
doc = false

[dependencies]
actix = "*"
actix-web = { version = "*", default-features = false, features = [ "rust-tls" ] }
clippy = { version = "*", optional = true }
ansi_term = "*"
bitflags = "*"
byteorder = "*"
clap = { version = "*", features = [ "suggestions", "color", "unstable" ] }
env_logger = "*"
features = "*"
futures = "*"
glob = "*"
hab = { path = "../hab" }
habitat_butterfly = { path = "../butterfly", default-features = false }
habitat_common = { path = "../common" }
habitat_core = { git = "https://github.com/habitat-sh/core.git" }
habitat_api_client = { path = "../builder-api-client" }
habitat-eventsrv-client = { path = "../eventsrv-client" }
habitat-launcher-client = { path = "../launcher-client" }
habitat-sup-protocol = { path = "../sup-protocol", default-features = false }
# The handlebars crate has a few issues that require us to lock at 0.28.3
# until further notice.
#
# - 0.30.0 bumps to a version of the `pest` crate that fails to build
#   on Windows.
# - 0.29.0 makes a change to array processing that is incompatible
#   with our templating syntax; we use "foo[0]", but it now requires
#   "foo.[0]"
#   See https://github.com/sunng87/handlebars-rust/commit/707f05442ef6f441a1cfc6b13ac180b78cb296db
handlebars = { version = "= 0.28.3", default-features = false }
lazy_static = "*"
libc = "*"
log = "*"
notify = "*"
prost = "*"
protobuf = { version = "1.5.1", features = ["bytes"] }
rand = "*"
regex = "*"
rust-crypto = "*"
rustls = "*"
serde = { version = "*", features = ["rc"] }
serde_derive = "*"
serde_json = "*"
serde_yaml = "*"
serde-transcode = "*"
tempfile = "*"
time = "*"
toml = { version = "*", default-features = false }
tokio = "*"
tokio-core = "*"
tokio-codec = "*"
url = "*"
valico = "*"

[target.'cfg(target_os = "linux")'.dependencies]
caps = "*"

[target.'cfg(windows)'.dependencies]
ctrlc = "*"
winapi = "*"

[dev-dependencies]
# Pending upgrade activities in https://github.com/habitat-sh/core/issues/72
hyper = "0.10"
json = "*"

[dev-dependencies.habitat_core]
git = "https://github.com/habitat-sh/core.git"

[features]
default = []
apidocs = []

